### ISSUE TITLE
容器运行正常，无法正常访问国际网络，日志报错

### ISSUE THREAD

**Issue by ghost** [wubaiqing/v2ray-docker-compose#1]
查看了日志，报错如下：
2020/08/29 16:11:26 [error] 19#19: send() failed (111: Connection refused) while resolving, resolver: 127.0.0.1:53
2020/08/29 16:11:26 [error] 19#19: send() failed (111: Connection refused) while resolving, resolver: 127.0.0.1:53
XXX.XXX.99.3 - - [29/Aug/2020:16:11:26 +0000] "GET /v2ray/ HTTP/1.1" 404 0 "-" "Go-http-client/1.1" "-"
2020/08/29 16:11:31 [error] 19#19: send() failed (111: Connection refused) while resolving, resolver: 127.0.0.1:53
2020/08/29 16:11:36 [error] 19#19: send() failed (111: Connection refused) while resolving, resolver: 127.0.0.1:53
2020/08/29 16:11:41 [error] 19#19: send() failed (111: Connection refused) while resolving, resolver: 127.0.0.1:53
2020/08/29 16:11:46 [error] 19#19: send() failed (111: Connection refused) while resolving, resolver: 127.0.0.1:53
2020/08/29 16:11:51 [error] 19#19: send() failed (111: Connection refused) while resolving, resolver: 127.0.0.1:53
2020/08/29 16:11:56 [error] 19#19: ocsp.int-x3.letsencrypt.org could not be resolved (110: Operation timed out) while requesting certificate status, responder: ocsp.int-x3.letsencrypt.org, certificate: "/etc/nginx/certs/v2ray.crt"
xxx.xxx.xxx.xxx - - [29/Aug/2020:16:12:15 +0000] "GET /v2ray HTTP/2.0" 400 12 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.135 Safari/537.36" "-"
27.46.99.3 - - [29/Aug/2020:16:14:28 +0000] "GET /v2ray/ HTTP/1.1" 404 0 "-" "Go-http-client/1.1" "-"
27.46.99.3 - - [29/Aug/2020:16:14:34 +0000] "GET /v2ray/ HTTP/1.1" 404 0 "-" "Go-http-client/1.1" "-"
27.46.99.3 - - [29/Aug/2020:16:14:36 +0000] "GET /v2ray/ HTTP/1.1" 404 0 "-" "Go-http-client/1.1" "-"
27.46.99.3 - - [29/Aug/2020:16:14:37 +0000] "GET /v2ray/ HTTP/1.1" 404 0 "-" "Go-http-client/1.1" "-"
27.46.99.3 - - [29/Aug/2020:16:14:37 +0000] "GET /v2ray/ HTTP/1.1" 404 0 "-" "Go-http-client/1.1" "-"
27.46.99.3 - - [29/Aug/2020:16:14:37 +0000] "GET /v2ray/ HTTP/1.1" 404 0 "-" "Go-http-client/1.1" "-"
27.46.99.3 - - [29/Aug/2020:16:14:37 +0000] "GET /v2ray/ HTTP/1.1" 404 0 "-" "Go-http-client/1.1" "-"
27.46.99.3 - - [29/Aug/2020:16:14:38 +0000] "GET /v2ray/ HTTP/1.1" 404 0 "-" "Go-http-client/1.1" "-"
27.46.99.3 - - [29/Aug/2020:16:14:38 +0000] "GET /v2ray/ HTTP/1.1" 404 0 "-" "Go-http-client/1.1" "-"
27.46.99.3 - - [29/Aug/2020:16:14:38 +0000] "GET /v2ray/ HTTP/1.1" 404 0 "-" "Go-http-client/1.1" "-"
27.46.99.3 - - [29/Aug/2020:16:14:42 +0000] "GET /v2ray/ HTTP/1.1" 404 0 "-" "Go-http-client/1.1" "-"
27.46.99.3 - - [29/Aug/2020:16:18:10 +0000] "GET / HTTP/1.1" 301 169 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.135 Safari/537.36" "-"

**Comment by wubaiqing** [comment]
解决了吗？你这份日志，最关键信息：
ocsp.int-x3.letsencrypt.org could not be resolved (110: Operation timed out) while requesting certificate status, responder: ocsp.int-x3.letsencrypt.org, certificate: "/etc/nginx/certs/v2ray.crt"
